FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add tzdata ca-certificates git

ARG TARGETARCH

COPY build/spage-linux-${TARGETARCH} /app/spage

RUN chmod +x /app/spage

ENTRYPOINT ["/app/spage"]