FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add tzdata ca-certificates git

ARG TARGETARCH

COPY build/spage-agent-linux-${TARGETARCH} /app/spage-agent

RUN chmod +x /app/spage-agent

ENTRYPOINT ["/app/spage-agent"]