import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { DeviceProvider } from "@/contexts/DeviceContext";
import I18nProvider from "@/providers/I18nProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ThemeProvider 只包裹 body 内容 */}
        <DeviceProvider>
          <I18nProvider>{children}</I18nProvider>
        </DeviceProvider>
      </body>
    </html>
  );
}
