import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Nav from "@/components/Nav";
import { DeviceProvider } from "@/contexts/DeviceContext";
import { SessionProvider } from "@/contexts/SessionContext";
import I18nProvider from "@/providers/I18nProvider";

import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 dark:bg-slate-800`}>
        {/* ThemeProvider 只包裹 body 内容 */}
        <SessionProvider>
          <DeviceProvider>
            <I18nProvider>
              {children}
            </I18nProvider>
          </DeviceProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
